### PR TITLE
fixes #143: offline fetch bug fixes for v4, TileJSON, and marker feature URL

### LINKED ISSUE #143: off-by-one bug with fetched markers URL 404'ing
Styles created with Mapbox Studio can't have markers, so their `markers.geojson` / `features.json` always `404` rather than return an empty collection. This creates an off-by-one bug in the offline downloading code. 

We need to refactor so that the markers (and possibly subsequent marker icon) URL fetches only happen if the metadata says so.

### PR DESCRIPTION
**Pull request by incanus**
Needs a quick review & merge by @incanus.

### CODE REVIEW

**Comment by incanus** [comment]
I think we should hit a couple light code quality details: 

 * Some minor comment lines left like [here](https://github.com/mapbox/mbxmapkit/blob/970fc91b8d12bf043b9adfd1bfc44c4d1a930bae/MBXMapKit/MBXOfflineMapDownloader.m#L427) & [here](https://github.com/mapbox/mbxmapkit/blob/970fc91b8d12bf043b9adfd1bfc44c4d1a930bae/MBXMapKit/MBXOfflineMapDownloader.m#L584-L588)
 * Variable naming like [here](https://github.com/mapbox/mbxmapkit/blob/970fc91b8d12bf043b9adfd1bfc44c4d1a930bae/MBXMapKit/MBXOfflineMapDownloader.m#L451)
 * Some log verbosity like [here](https://github.com/mapbox/mbxmapkit/blob/970fc91b8d12bf043b9adfd1bfc44c4d1a930bae/MBXMapKit/MBXOfflineMapDownloader.m#L428) & [here](https://github.com/mapbox/mbxmapkit/blob/970fc91b8d12bf043b9adfd1bfc44c4d1a930bae/MBXMapKit/MBXOfflineMapDownloader.m#L472)

**Comment by wsnook** [comment]
@incanus have you had a chance to look at https://github.com/mapbox/mbxmapkit/issues/149? Maybe @vinod1988's error message won't tell you anything you didn't already know, but it appears to have something to do with `startDownloading:` which gets changed in this PR. No mention of markers though.

**Comment by incanus** [comment]
@wsnook Yeah, thanks, let's see if we can repro and get more details about version there. 

@bleege Is the stuff in https://github.com/mapbox/mbxmapkit/pull/147#issuecomment-72134458 something you can hit while I try out functionality here in prep for release?

**Comment by bleege** [comment]
@incanus I'd be happy to... link is bad though.  Are you referring to #149?  If so I looked at it this morning and I think this PR will help address it.

**Comment by incanus** [comment]
No, sorry, I mean the three bullet points two comments above my last, about log verbosity, comments, and variable naming.

**Comment by bleege** [comment]
Ah!  Will do.

**Comment by incanus** [comment]
I occasionally got some non-resumed downloads when going through test patterns of `v3` & `v4` start, pause, resume, and quit/restart app, but couldn't accurately repro a fail condition. 

Along the way, though, I noticed logging like this: 

```
2015-02-03 15:16:57.899 MBXMapKit[88865:3900456] total expected: 1423; total actually: 567
2015-02-03 15:16:57.900 MBXMapKit[88865:3900456] pathExtension = 'png'
2015-02-03 15:16:57.900 MBXMapKit[88865:3899954] total expected: 1423; total actually: 567
2015-02-03 15:16:57.900 MBXMapKit[88865:3899954] pathExtension = 'png'
2015-02-03 15:16:57.901 MBXMapKit[88865:3900456] total expected: 1423; total actually: 567
2015-02-03 15:16:57.901 MBXMapKit[88865:3900456] pathExtension = 'png'
2015-02-03 15:16:57.937 MBXMapKit[88865:3900456] total expected: 1423; total actually: 570
2015-02-03 15:16:57.938 MBXMapKit[88865:3900456] pathExtension = 'png'
2015-02-03 15:16:58.002 MBXMapKit[88865:3899954] total expected: 1423; total actually: 571
2015-02-03 15:16:58.002 MBXMapKit[88865:3899954] pathExtension = 'png'
2015-02-03 15:16:58.003 MBXMapKit[88865:3899952] total expected: 1423; total actually: 571
2015-02-03 15:16:58.004 MBXMapKit[88865:3899952] pathExtension = 'png'
2015-02-03 15:16:58.004 MBXMapKit[88865:3899952] total expected: 1423; total actually: 571
2015-02-03 15:16:58.004 MBXMapKit[88865:3899952] pathExtension = 'png'
2015-02-03 15:16:58.027 MBXMapKit[88865:3899943] total expected: 1423; total actually: 574
2015-02-03 15:16:58.027 MBXMapKit[88865:3899943] pathExtension = 'png'
2015-02-03 15:16:58.096 MBXMapKit[88865:3899943] total expected: 1423; total actually: 575
2015-02-03 15:16:58.096 MBXMapKit[88865:3899943] pathExtension = 'png'
2015-02-03 15:16:58.096 MBXMapKit[88865:3899943] total expected: 1423; total actually: 575
2015-02-03 15:16:58.097 MBXMapKit[88865:3899943] pathExtension = 'png'
2015-02-03 15:16:58.105 MBXMapKit[88865:3899943] total expected: 1423; total actually: 577
2015-02-03 15:16:58.105 MBXMapKit[88865:3899943] pathExtension = 'png'
```

The fact that some numbers are skipped and others are duped, makes me fear a possible race condition, but it could merely be a result of `NSLog` (actually, `NSLogv` under the hood dropping some lines: 

> Output from `NSLogv` is serialized, in that only one thread in a process can be doing the writing/logging described above at a time.

**Comment by bleege** [comment]
@incanus Just finished the code cleanup.

**Comment by incanus** [comment]
Per chat with @willwhite we are going to pull `v3` access from the library, so we should hit it here before merge since there's logic around `markers.geojsonp` vs. `features.json`, appending query string for token, and stuff like that.

**Comment by incanus** [comment]
Hitting this post-GL sprint, when we can merge & do a point release. @bleege

**Comment by bleege** [comment]
:+1:

**Pull request closed without merging**
