### PR TITLE
MBTiles overzoom implementation for #3 / #42

### PR DESCRIPTION
**Pull request by wsnook**
Here's another candidate for closing the long-standing #3, "add MBTiles support" ticket. This implementation is the simplest thing I could come up with to do an MBTiles MKTileOverlay subclass with overzooming (see #42). Since this code is fairly compact and self contained, I'm hoping it will be an easy merge.

There have been a few attempts at doing this in the past (#20 , #110, #119). So, how is this one different, and why am I submitting it now? Well, fairly recently I received a private request to get a working MBTiles overlay class going with overzooming. I did that by cobbling together bits of code from various un-merged commits, cleaning things up, and adding some new code. Now since I've got something which works pretty well, I would like to contribute the results back to MBXMapKit.

## Q&A

**Q:** What does this implementation do?
**A:** It provides an MBTiles tile overlay with overzooming. There is one option for initialization (the path to an mbtiles file on disk) and two properties read from the MBTiles metadata table (attribution and maximum zoom).

**Q:** Why doesn't it do ____?
**A:** My goal was to make something simple which could be easily used, easily merged, and extended in the future if the need arises. Based on discussions over the past year in the MBXMapKit issues list, it seems that for MBTiles to be useful, overzooming is essential. Attribution is essential for meeting legal requirements. Beyond that, lots of things might be nice, but they are not essential. I've tried to omit non-essential things to make for an easy merge.

**Q:** Why is the MBTiles code in its own directory with its own sample app?
**A:** I'm hoping this will provide a low friction path for merging the MBTiles code now and eventually migrating it into the main MBXMapKit API. The UI for selecting between examples in the existing MBXMapKit sample app is maxed out. It currently doesn't have the capacity to accommodate additional examples (see https://github.com/mapbox/mbxmapkit/issues/89). Also, the MBTiles code does not have any natural dependencies on, or interactions with, the existing MBXMapKit API -- MBTiles needs libsqlite3 and MapKit, but that's all. Putting the MBTiles overzoom code in its own folder for now will make it visible and available to use and will also leave the door open for someone to fix the main sample app and migrate the MBTiles code into the main API.

**Q:** Why does this just do overzooming for MBTiles instead of overzooming for all tile sources?
**A:** To do overzooming, you need three things from your tile source: one, metadata for the maximum zoom level; two, metadata for whether the Y axis is flipped; three, a way to fetch tiles from the tile source's maximum zoom level. For an MBTiles specific overzoom implementation, all of those things are quite straightforward and the necessary code is very compact. As soon as you start trying to do general-case overzooming, you have to start worrying about caching, asynchronous requests, etc, etc. None of those things are inherently very difficult, but they would add up to a significant amount of extra complexity in the pull request. My intent here is specifically to provide a simple overzooming MBTiles overlay, leaving the door open for others to extend things in the future.

cc @incanus

### CODE REVIEW

**Comment by Nicolastriplec** [comment]
Hi there, I m getting the error  <Error>: ImageIO: CGImageSourceCreateWithData data parameter is nil, it seams that in the normal branch it is solved by a custom render, can you do the same with this build? thanks!

**Comment by wsnook** [comment]
@Nicolastriplec I just synced my fork by merging several new commits from `mapbox:master` into `wsnook:master`. The error message you mentioned should stop if your mapview delegate uses the new `MBXRasterTileRenderer` class instead of Apple's `MKTileOverlayRenderer` class.

My sample app for the MBTiles overzoom stuff still uses `MKTileOverlayRenderer` (see [ViewController.m](https://github.com/wsnook/mbxmapkit/blob/b35b53e697a5b8b3cfadfcffa7dacac84bf84e14/MBTilesOverzoom/MBTiles%20Sample%20Project/MBTiles%20Sample%20Project/ViewController.m#L36-39) in the MBTilesOverzoom sample app) because I would like to minimize dependencies between my overzoom code and the rest of MBXMapKit (see my comments about that above). However, if you would like to try using `MBXRasterTileRenderer`, presumably you can just include `MBXRasterTileRenderer.h` and change your `mapView:rendererForOverlay:` (see the [MBXViewController.m](https://github.com/wsnook/mbxmapkit/blob/b35b53e697a5b8b3cfadfcffa7dacac84bf84e14/Sample%20Project/MBXMapKit%20iOS/MBXViewController.m#L514-518) in the main sample app). I haven't tested whether it works, but I don't know of any reason why it wouldn't.

**Comment by Nicolastriplec** [comment]
I did it, but for the moment tiles appear upside down in the world map. I suppose I must to change your overlay class for a correct rendering... And instead the error message disappear, the app crashes randomly when map is changing the region... With the normal render my app never crashed.

**Comment by wsnook** [comment]
@Nicolastriplec I'm not familiar with the details of how @incanus implemented `MBXRasterTileRenderer`, but I do know that sometimes tile sources which have an inverted Y axis require different calculations than tile sources with a regular Y axis. For my overzooming code in this pull request, I used math which assumed that the Y axis used the default arrangement for an MBTiles file created by TileMill 1.

If I were in your position, I would probably just use `MKTileOverlayRenderer` and ignore the log messages about "CGImageSourceCreateWithData data parameter is nil". While the log messages are certainly annoying, they should be relatively harmless as far as I know. If you haven't already, you should probably read the whole thread for issue  https://github.com/mapbox/mbxmapkit/issues/132 which talks about the "...data parameter is nil" log messages and `MKTileOverlayRenderer`. Hopefully Apple will fix the problem in a future iOS update.

If you're having crashing problems with `MBXRasterTileOverlayRenderer` which you can reproduce using the `mapbox:master` branch, you might consider creating a separate issue about the crashing rather than posting more details on this pull request.

Good luck.

**Comment by wsnook** [comment]
@Nicolastriplec you might also want to take a look at issue https://github.com/mapbox/mbxmapkit/issues/152 to see if the crash log there looks anything like the crashing that you saw while changing regions with `MBXRasterTileRenderer`.

**Comment by johndpope-karhoo** [comment]
I like this clean and simple implementation. Did you ever look at using vector tiles with mbtiles?

**Comment by wsnook** [comment]
If anybody happens to wander here from google or get a notification about this comment, here's a quick explanation of why I'm closing this pull request after so much time has passed.

I got a question today about this PR, so I thought it would be good to clarify that mbxmapkit is a deprecated project (see the project description at https://github.com/mapbox/mbxmapkit). If you want more info on Mapbox's current options for iOS, you should probably start by taking a look at https://www.mapbox.com/mobile/

**Pull request closed without merging**
