### PR TITLE
custom raster tile renderer (work around iOS 8 bug, support 512px v4 tiles)

### PR DESCRIPTION
**Pull request by incanus**

### CODE REVIEW

**Comment by robmaceachern** [comment]
I'm seeing a pretty consistent crash when running the sample project on the 132-renderer branch. It's failing in ```MBXRasterTileRenderer canDrawMapRect:(MKMapRect)mapRect zoomScale:(MKZoomScale)zoomScale```

Here's the [crash report](http://textuploader.com/6dev). I was seeing it on iPhone 6 iOS 8.1.1.

**Comment by incanus** [comment]
Thanks for that, @robmaceachern. I'll check it out.

**Comment by incanus** [comment]
@robmaceachern Can you give the latest iteration of the branch (with 3f5cfa7515f5806e78b00171a780e3bc43f0deea) a try? The crash logs seems to say that this is related to use of `-[UIImage imageWithData:]` in background threads, which seems to be unadvisable if you take the strictly conservative approach based on: 

http://stackoverflow.com/questions/12766501/is-creating-uiimage-thread-safe

That is, UIKit clearly shouldn't draw or update UI from background threads, but it's open to interpretation whether image instantiation is ok. 

Also, note that at least in my device testing, using a `Release` build is noticeably faster, so do check that out if performance is a concern.

**Comment by incanus** [comment]
Trying to push a bit more of the image work out to `CGImageRef` and friends instead of dispatching to the main thread. Just about there.

**Comment by robmaceachern** [comment]
I was hoping it was going to be that easy too, but there's something else going on. :cry: 

screen shot 2015-01-14 at 4 58 12 pm

It seems like the ```tileData``` is (intermittently) bogus.

**Comment by incanus** [comment]
@robmaceachern The thing I don't understand about that is how that point in the control flow is reached then, since just three lines above, there is an `if (tileData) {`. That's what leads me to think that it's threading related with UIKit.

**Comment by tkrajacic** [comment]
Self can go away between those lines.
Wasn't there an issue last year where we tried to figure something like this out? I can't find it though.

**Comment by incanus** [comment]
`self` could, yes, since it's the `MKMapView` in question inside of that `loadTileAtPath:result:` callback, but it doesn't — the map view stays put. So I'm thinking this is related to creation of `UIImage` objects happening in non-main threads; something about the way graphics memory is allocated or used, maybe?

**Comment by robmaceachern** [comment]
@incanus ```tileData``` is not nil at that point which is why it passes the conditional test. I've also experimented with core graphics and experienced the same issue, so we can rule out UIKit issues.

I just noticed your commit. I'll try to reproduce the problem again.

**Comment by incanus** [comment]
Yeah, please see if you can reproduce. I cut out all use of `UIImage` initialization since we're never on the main thread by default. 

Now I'm working on performance — I don't like it, and ~40% of the time is spent in PNG encoding after slicing `512px` tiles into `256px` tiles in the `-canDrawMapRect:zoomScale:`. Thinking I'll just move to raw pixels instead of PNG data since we're only talking about in-memory storage anyway (I thought it best to never cache on disk the `256px` sliced tiles since we never request them directly in the API).

**Comment by robmaceachern** [comment]
Yeah it's still an issue. It's failing at the same CG function as before ```_CGImageSourceBindToPlugin ()```

screen shot 2015-01-15 at 11 02 31 am

**Comment by robmaceachern** [comment]
Just got another, different, EXC_BAD_ACCESS in some system networking code while running on the iPhone 6 simulator.

```
#0	0x000000010e85562a in getMIMETypeForRuleArray(__CFData const*, MIMETypeRule const*, unsigned char) ()
#1	0x000000010e7e0690 in URLResponse::guessMIMETypeCurrent(__CFData const*) ()
#2	0x000000010e849e08 in -[__NSCFURLSessionConnection _tick_sniffNow] ()
#3	0x000000010e849eb6 in -[__NSCFURLSessionConnection _tick_running] ()
#4	0x000000010e84d0d2 in SessionConnectionLoadable::_loaderClientEvent_DidReceiveData(__CFArray const*) ()
#5	0x000000010e84d216 in SessionConnectionLoadable::_loaderClientEvent_HandleCacheResponseIsValid(_CFCachedURLResponse const*) ()
#6	0x000000010e8b7e2f in ___ZN19URLConnectionLoader28protocolCacheResponseIsValidEPK20_CFCachedURLResponse_block_invoke ()
#7	0x000000010e84c943 in ___ZN25SessionConnectionLoadable21withLoaderClientAsyncEU13block_pointerFvP21LoaderClientInterfaceE_block_invoke ()
#8	0x000000010de37ba6 in _dispatch_call_block_and_release ()
#9	0x000000010de557f4 in _dispatch_client_callout ()
#10	0x000000010de3db22 in _dispatch_queue_drain ()
#11	0x000000010de3d432 in _dispatch_queue_invoke ()
#12	0x000000010de3ffc1 in _dispatch_root_queue_drain ()
#13	0x000000010de415d9 in _dispatch_worker_thread3 ()
#14	0x000000010e1d96cb in _pthread_wqthread ()
#15	0x000000010e1d74a1 in start_wqthread ()
Enqueued from __NSCFURLSessionConnection (Thread 24)Queue : __NSCFURLSessionConnection (serial)
```

**Comment by incanus** [comment]
Storing raw pixel data in the memory cache isn't much faster, and the bottleneck is copying the individual `CGImageRef` data there. 

Trying the approach now of caching the `CGImageRef` pointers (after retaining their data) and seeing if that helps.

**Comment by incanus** [comment]
Just a summary, for my own reference (since I had to re-look it up to remind myself) on why we are splitting `512px` tiles client-side: 

1. iOS 7 has a bug where `MKTileOverlay` cannot use tiles of sizes larger than `256px`. 
1. iOS 8 has a bug where using `MKTileOverlay` logs lots of `ImageIO` warnings and occasionally crashes and/or doesn't draw tiles. 
1. Both of the above can be solved by creating a custom `MKTileOverlayRenderer`, but per https://github.com/mapbox/mbxmapkit/issues/132#issuecomment-65486844 it is not possible to draw in areas greater than `256px` in a custom renderer.

**Comment by incanus** [comment]
Ok, more performance and reliability work here. 

Now, instead of splitting `512px` tiles in the *ready to draw?* routine, instead they are being cached once there. Then, when the child `256px` tile is subsequently asked to draw, the parent tile data is fetched, rasterized, and then cropped in the same routine as the drawing into the request context, to localize all Core Graphics work. 

All drawing work is still done in background threads and using `CGImageRef` and friends, plus `ImageIO.framework` is still not needed. 

I'd love to see how this works for folks. /cc @robmaceachern

**Comment by robmaceachern** [comment]
I still experience the crash in https://github.com/mapbox/mbxmapkit/pull/136#issuecomment-70141819

**Comment by incanus** [comment]
@robmaceachern What does your `tileData` look like there; PNG or JPEG? Can you share the `mapID` you are using?

**Comment by incanus** [comment]
Better yet, give things a try now — proper detection of image format rather than trial & error.

**Comment by robmaceachern** [comment]
I'm just running the sample application. Map id: examples.map-pgygbwdm and access token pk.eyJ1IjoianVzdGluIiwiYSI6IlpDbUJLSUEifQ.4mG8vhelFMju6HpIY-Hi5A.

Still getting exc_bad_access errors using iPhone 6 on 8.1.2. Are you not able to reproduce?

screen shot 2015-01-16 at 3 14 37 pm

screen shot 2015-01-16 at 3 10 32 pm

Also, the simulator seems to be rendering incorrectly.

screen shot 2015-01-16 at 3 19 32 pm

**Comment by incanus** [comment]
No, I'm never seeing these exact crashes. Will try with those settings.

**Comment by incanus** [comment]
Ok, could replicate an a retina iPad mini, to the first crash in PNG detection. Will keep digging. Thanks @robmaceachern!

**Comment by robmaceachern** [comment]
No problem @incanus. Good luck tracking that down – I wasn't getting anywhere.

**Comment by incanus** [comment]
Ok, a very promising lead now. 

https://github.com/mapbox/mbxmapkit/commit/40f71def4588deb10cabd1cb1914cbd2e6cbef30 brings in a change that calls `-loadTileAtPath:result:` synchronously. There is nothing in the docs that says whether async is ok here, just that it should call from the main thread. In our own implementation of that method, like most sane implementations we kick off to a background thread anyway for the actual loading heavy lifting, but I think these chained async calls are, under high system load, possibly causing `result()`'s data to be released early. You'd think block scope would capture it properly, but I think you'd be wrong. There is no reason to call `result()` async here anyway, so it strikes me as possibly a Bad Idea and the root of our problems. 

I also added https://github.com/mapbox/mbxmapkit/commit/c7a82c37d1b5dc7b792670cccdf8d9d0fc33874f, which responds to low system memory and jettisons the in-memory cache of tiles, which seems like a good idea given the amount of memory we're talking about. However, in lots of testing on a retina iPad, even with 300-400MB of app memory usage I wasn't able to trigger it very often.

**Comment by incanus** [comment]
Yet another very promising lead, the best one yet. Even with the above, I was able to reproduce the crash again. I investigated the `NSData` passed in the callback, and its underlying type was `OS_dispatch_data`, which makes a bit of sense. 

However, this sounds rather transient and is probably going away out from under us. Trying either an `-[NSData copy]` or an `+[NSData dataWithData:]` to keep it around both yield identical types under the hood, like so: 

```
2015-01-16 16:30:56.987 MBXMapKit[1242:317501] old: OS_dispatch_data
2015-01-16 16:30:56.987 MBXMapKit[1242:317501] new: OS_dispatch_data
```

No dice. However 226edce5e2cee4e25a1c6f9dbfe235e607ffa8d9 uses `-[NSData initWithBytes:length:]` per [CocoaDev](http://cocoadev.com/DeepCopyingNSData), which does yield a fresh copy & new type: 

```
2015-01-16 16:30:30.669 MBXMapKit[1220:317060] old: OS_dispatch_data
2015-01-16 16:30:30.669 MBXMapKit[1220:317060] new: _NSInlineData
```

This copy happens in the main thread, then the copy is captured in the async block scope and dealt with (validated & cached) off the main thread, then ARC disposes of it, regardless of what has already happened with the original dispatched version's lifetime. 

And **now** I've been unable to replicate the crash.

**Comment by robmaceachern** [comment]
No dice. ```tileData``` is still going bad.

screen shot 2015-01-16 at 6 03 59 pm

I think this may be an NSURLSession bug. I tried copying it in the data task handler and it still fails.

screen shot 2015-01-16 at 6 13 39 pm

**Comment by incanus** [comment]
> I think this may be an NSURLSession bug. I tried copying it in the data task handler and it still fails.

Could be, but Occam's Razor says it's something we're doing. My guess could be maybe something around the passing of `result` inside of `completionHandler` and ARC not understanding proper lifetime scope. Will keep digging at this.

**Comment by incanus** [comment]
> this may be an NSURLSession bug

Gonna try gutting this for `NSURLConnection`, I think, and see how that fares.

**Comment by incanus** [comment]
Ok, tried a number of approaches around reducing nesting of blocks, manually copying blocks, and otherwise being very explicit around blocks, with no luck. 

Went the route of replacing `NSURLSession` with `NSURLConnection` in the overlay. The downside is we lose the ability to specify the number of concurrent HTTP connections per host and the ability to summarily cancel all pending fetches as in `NSURLSession`, but I think it's a fair tradeoff and I'm not seeing a performance consequence. 

Curious how this works for you, @robmaceachern.

**Comment by incanus** [comment]
I've yet to replicate a crash here since moving to `NSURLConnection`. I need to benchmark a bit more between `Debug` and `Release` — I feel like this could be slower. But then again, maybe not, as we are slicing `512px` tiles on the client to accomplish this. /cc @willwhite

**Comment by incanus** [comment]
Yeah, there's plenty of duplicate URL fetching going on here in response to MapKit's impatience. Will work on this. 

```
2015-01-27 15:28:49.692 MBXMapKit[263:13405] 16,10556,25512 start
2015-01-27 15:28:49.693 MBXMapKit[263:13409] 16,10556,25512 start
2015-01-27 15:28:49.694 MBXMapKit[263:13411] 16,10556,25512 start
2015-01-27 15:28:49.695 MBXMapKit[263:13408] 16,10555,25512 start
2015-01-27 15:28:49.695 MBXMapKit[263:13410] 16,10555,25512 start
2015-01-27 15:28:49.696 MBXMapKit[263:13413] 16,10558,25511 start
2015-01-27 15:28:49.696 MBXMapKit[263:13376] 16,10555,25512 start
2015-01-27 15:28:49.697 MBXMapKit[263:13412] 16,10557,25511 start
2015-01-27 15:28:49.698 MBXMapKit[263:13375] 16,10555,25512 start
2015-01-27 15:28:49.698 MBXMapKit[263:13414] 16,10557,25511 start
2015-01-27 15:28:49.699 MBXMapKit[263:13383] 16,10556,25511 start
2015-01-27 15:28:49.700 MBXMapKit[263:13416] 16,10556,25511 start
2015-01-27 15:28:49.700 MBXMapKit[263:13417] 16,10555,25511 start
2015-01-27 15:28:49.702 MBXMapKit[263:13418] 16,10555,25511 start
2015-01-27 15:28:50.095 MBXMapKit[263:13170] 16,10558,25515 end
2015-01-27 15:28:50.097 MBXMapKit[263:13170] 16,10558,25515 end
2015-01-27 15:28:50.148 MBXMapKit[263:13170] 16,10557,25515 end
2015-01-27 15:28:50.165 MBXMapKit[263:13170] 16,10557,25515 end
2015-01-27 15:28:50.191 MBXMapKit[263:13170] 16,10557,25515 end
2015-01-27 15:28:50.195 MBXMapKit[263:13170] 16,10557,25515 end
2015-01-27 15:28:50.573 MBXMapKit[263:13170] 16,10556,25515 end
2015-01-27 15:28:50.606 MBXMapKit[263:13170] 16,10556,25515 end
2015-01-27 15:28:50.608 MBXMapKit[263:13170] 16,10556,25515 end
```

**Comment by incanus** [comment]
Ok, the duplicates were somewhat expected given that requests made for to-be-split `512px` tiles come in fours. However, we were possibly kicking off up to four duplicate HTTP requests at once, when one is enough to split and satisfy four sub-tile would-be requests. This works better now.

**Comment by robmaceachern** [comment]
No crashes for me :+1: 

Have you filed a radar for the NSURLSession issue?

**Comment by incanus** [comment]
> Have you filed a radar for the NSURLSession issue?

No, nor for the three MapKit bugs I am seeing around this. Will hopefully make up use cases for these & submit them.

**Comment by jsuder** [comment]
This branch fixes the log warnings for me too. No crashes, but I've only scrolled it around for a short moment.

**Comment by incanus** [comment]
Thanks @robmaceachern @jsuder for your patience and testing! I am feeling good about this and it's landed in `master`.

**Comment by incanus** [comment]
@jsuder Hmm, that's deep in MapKit, and I haven't seen it before. Can you reliable replicate it? Device or sim? Particular UI interactions?

**Comment by jsuder** [comment]
I've only seen it twice today and I've run the app many times... It's on
the simulator and I'm not doing any interactions, just showing the map
centered on a specific point.

**Pull request closed without merging**
